name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run:   |
         sudo apt update
         sudo apt install gcc-10 g++-10
    - uses: actions/checkout@v3
    - name: create directory
      run: mkdir output
    - name: make
      run: make
    - name: test
      run: output/comp.out test.asm
      env:
       CC:   gcc-10
       CXX:  g++-10
    - name: test2
      run: output/emu.out out.bin
      env:
       CC:   gcc-10
       CXX:  g++-10
